### ISSUE TITLE
Sada alespoň tří netriviálních testovacích metod k vašemu projektu

### ISSUE THREAD

**Issue by janinko** [janinko/Java---Evidence-CD#1]
Úloha 2

Název: Sada alespoň tří netriviálních testovacích metod k vašemu projektu
Počet bodů: 3
Způsob řešení: Každý člen týmu řeší úlohu zvlášť a vytváří různé testovací metody pro různé části aplikace.

**Comment by ghost** [comment]
he :P

**Comment by janinko** [comment]
ja už minimálně tři metody mám a ty určitě taky :)

**Comment by ghost** [comment]
jj, testy pro splneni ukolu jsou jiz ok
